import { describe, expect, test } from "bun:test";
import { readSessionCookie, sessionCookie } from "../src/auth.ts";
import { listAllRecords, parseConfig, PdsService, validateMediaUrl } from "../src/pds.ts";
const secret = "a-secret-longer-than-thirty-two-characters";
describe("cloud auth and PDS records", () => {
  test("auth cookie is signed and rejects tampering", async () => { const value = await sessionCookie("did:plc:alice", secret); expect(await readSessionCookie(new Request("https://example.test", { headers: { cookie: `stream_overlay_session=${value}` } }), secret)).toBe("did:plc:alice"); expect(await readSessionCookie(new Request("https://example.test", { headers: { cookie: `stream_overlay_session=${value}x` } }), secret)).toBeUndefined(); });
  test("parses command records and converts storage units", () => { const namespace="invalid.streamoverlay.dev"; const result=parseConfig({$type:`${namespace}.settings`,enabled:true,streamerDid:"did:plc:alice",updatedAt:"v1"},[{$type:`${namespace}.command`,id:"one",command:"wave",mode:"effect",durationMilliseconds:1500,cooldownSeconds:20,volumePercent:55,width:"",height:"",mirrored:false}],namespace); expect(result?.commands[0].durationSeconds).toBe(1.5); expect(result?.commands[0].volume).toBe(.55); });
  test("only accepts HTTPS direct URL candidates", () => { expect(validateMediaUrl("https://cdn.example/clip.mp4")).toBe("https://cdn.example/clip.mp4"); expect(validateMediaUrl("http://cdn.example/clip.mp4")).toBeUndefined(); });
  test("paginates record reads", async () => { const cursors: Array<string|undefined>=[]; const records=await listAllRecords(async cursor=>{cursors.push(cursor);return cursor?{records:[{id:2}]}:{records:[{id:1}],cursor:"next"}}); expect(cursors).toEqual([undefined,"next"]); expect(records.map(item=>item.id)).toEqual([1,2]); });
  test("saves settings, command changes, and deletions in one conflict-checked repo write", async () => { const calls:any[]=[]; const agent:any={com:{atproto:{sync:{getLatestCommit:async()=>({data:{cid:"bafyhead"}})},repo:{getRecord:async()=>({data:{}}),listRecords:async()=>({data:{records:[{uri:"at://did:plc:alice/invalid.streamoverlay.dev.command/old"}]}}),applyWrites:async(input:any)=>{calls.push(input);return{data:{}}}}}},uploadBlob:async()=>({data:{blob:{}}})}; const service=new PdsService({restore:async()=>({})} as any,"invalid.streamoverlay.dev",0,0,{agent:()=>agent}); const saved=await service.save("did:plc:alice",{enabled:true,streamerDid:"did:plc:alice",revision:"old",commands:[{id:"new",command:"wave",mode:"effect",durationSeconds:1,cooldownSeconds:2,volume:.5,width:"40vw",height:"",mirrored:false}]}); expect(saved.revision).not.toBe("old"); expect(calls).toHaveLength(1); expect(calls[0].swapCommit).toBe("bafyhead"); expect(calls[0].writes.map((write:any)=>write.$type)).toEqual(["com.atproto.repo.applyWrites#update","com.atproto.repo.applyWrites#delete","com.atproto.repo.applyWrites#create"]); });
  test("first save can toggle enabled with no command or media records", async () => { const calls:any[]=[]; const missing=Object.assign(new Error("RecordNotFound"),{status:400}); const agent:any={com:{atproto:{sync:{getLatestCommit:async()=>({data:{cid:"bafyhead"}})},repo:{getRecord:async()=>{throw missing},listRecords:async()=>({data:{records:[]}}),applyWrites:async(input:any)=>{calls.push(input);return{data:{}}}}}},uploadBlob:async()=>({data:{blob:{}}})}; const service=new PdsService({restore:async()=>({})} as any,"invalid.streamoverlay.dev",0,0,{agent:()=>agent}); const saved=await service.save("did:plc:alice",{enabled:false,streamerDid:"did:plc:alice",revision:"new",commands:[]}); expect(saved.enabled).toBe(false); expect(calls[0].writes).toHaveLength(1); expect(calls[0].writes[0].$type).toBe("com.atproto.repo.applyWrites#create"); });
});
