type Media = { url?: string; blob?: unknown };
type Command = { id:string; command:string; mode:"effect"|"sticker"; image?:Media; audio?:Media; video?:Media; durationSeconds:number; cooldownSeconds:number; volume:number; width:string; height:string; mirrored:boolean };
type Config = { enabled:boolean; streamerDid:string; revision:string; commands:Command[] };
const app=document.querySelector<HTMLElement>("#app")!; let did=""; let config:Config; let editing:string|undefined; let pending:Partial<Record<"image"|"audio"|"video",Media>>={};
app.innerHTML=`<h1>Stream Overlay Cloud</h1><section class="login"><p>Sign in with your AT Protocol account to manage Emoticons stored on your PDS.</p><form class="login-form"><input name="handle" placeholder="handle.bsky.social" required><button>Sign in</button></form></section><section class="editor" hidden><p>Signed in as <code class="did"></code> <button class="logout">Log out</button></p><label><input class="enabled" type="checkbox"> Emoticons enabled</label><p>OBS effects: <code class="effect-url"></code></p><p>OBS board: <code class="board-url"></code></p><h2>Commands</h2><div class="commands"></div><button class="new">Create command</button><form class="command-form" hidden><h3 class="form-title"></h3><label>Command <input name="command" required pattern="[a-z0-9_-]{1,40}" placeholder="wow"></label><label><input name="sticker" type="checkbox"> Sticker mode</label><div class="drop" tabindex="0">Drop image/GIF, audio, or video here, or <input name="files" type="file" multiple accept="image/*,audio/*,video/*"></div><div class="attachments"></div><fieldset><legend>Direct media URLs (must be direct HTTPS files, not provider pages)</legend><label>Image/GIF URL <input name="imageUrl" type="url" placeholder="https://…/image.gif"></label><label>Audio URL <input name="audioUrl" type="url" placeholder="https://…/sound.mp3"></label><label>Video URL <input name="videoUrl" type="url" placeholder="https://…/clip.mp4"></label></fieldset><div class="row"><label>Duration <input name="duration" type="number" min="0.1" max="3600" step="0.1" value="5"></label><label>Cooldown <input name="cooldown" type="number" min="0" max="86400" step="1" value="20"></label><label>Volume <input name="volume" type="range" min="0" max="1" step="0.05" value="1"></label></div><div class="row"><label>CSS width <input name="width" placeholder="40vw"></label><label>CSS height <input name="height" placeholder="35vh"></label><label><input name="mirrored" type="checkbox"> Mirror</label></div><button>Save command</button><button class="cancel" type="button">Cancel</button></form><p class="status"></p></section>`;
const login=app.querySelector<HTMLElement>(".login")!, editor=app.querySelector<HTMLElement>(".editor")!, statusEl=app.querySelector<HTMLElement>(".status")!, commandForm=app.querySelector<HTMLFormElement>(".command-form")!, commandsEl=app.querySelector<HTMLElement>(".commands")!;
app.querySelector<HTMLFormElement>(".login-form")!.onsubmit=event=>{event.preventDefault();const handle=new FormData(event.currentTarget as HTMLFormElement).get("handle");location.href=`/oauth/login?handle=${encodeURIComponent(String(handle))}`};
function obsUrl(path:string){const url=new URL(path,location.origin);url.searchParams.set("did",did);return url.toString()}
function render(){commandsEl.replaceChildren();for(const command of config.commands){const row=document.createElement("div");row.className="row";const label=document.createElement("strong");label.textContent=`!${command.command} · ${command.mode}`;const edit=document.createElement("button");edit.textContent="Edit";edit.onclick=()=>open(command);const remove=document.createElement("button");remove.textContent="Delete";remove.onclick=()=>{config.commands=config.commands.filter(item=>item.id!==command.id);void saveAll();render()};row.append(label,edit,remove);commandsEl.append(row)}}
function mediaUrl(media?:Media){return media?.url??""}
function open(command?:Command){editing=command?.id;pending={image:command?.image,audio:command?.audio,video:command?.video};commandForm.hidden=false;(commandForm.elements.namedItem("command") as HTMLInputElement).value=command?.command??"";(commandForm.elements.namedItem("sticker") as HTMLInputElement).checked=command?.mode==="sticker";(commandForm.elements.namedItem("imageUrl") as HTMLInputElement).value=mediaUrl(command?.image);(commandForm.elements.namedItem("audioUrl") as HTMLInputElement).value=mediaUrl(command?.audio);(commandForm.elements.namedItem("videoUrl") as HTMLInputElement).value=mediaUrl(command?.video);(commandForm.elements.namedItem("duration") as HTMLInputElement).value=String(command?.durationSeconds??5);(commandForm.elements.namedItem("cooldown") as HTMLInputElement).value=String(command?.cooldownSeconds??20);(commandForm.elements.namedItem("volume") as HTMLInputElement).value=String(command?.volume??1);(commandForm.elements.namedItem("width") as HTMLInputElement).value=command?.width??"";(commandForm.elements.namedItem("height") as HTMLInputElement).value=command?.height??"";(commandForm.elements.namedItem("mirrored") as HTMLInputElement).checked=command?.mirrored??false;attachments()}
function attachments(){app.querySelector(".attachments")!.textContent=Object.entries(pending).filter(([,value])=>value).map(([kind])=>`${kind} uploaded to PDS`).join(" · ")}
async function upload(files:FileList|File[]){for(const file of Array.from(files)){const kind=file.type.startsWith("image/")?"image":file.type.startsWith("audio/")?"audio":file.type.startsWith("video/")?"video":undefined;if(!kind){statusEl.textContent=`Unsupported file: ${file.name}`;continue}if((commandForm.elements.namedItem("sticker") as HTMLInputElement).checked&&kind==="audio"){statusEl.textContent="Stickers cannot include audio.";continue}statusEl.textContent=`Uploading ${file.name}…`;const response=await fetch(`/api/accounts/${encodeURIComponent(did)}/media`,{method:"POST",headers:{"Content-Type":file.type},body:file});if(!response.ok){statusEl.textContent=`Upload failed: ${file.name}`;continue}pending[kind]={blob:await response.json()};if(kind==="image")delete pending.video;if(kind==="video")delete pending.image;attachments()}statusEl.textContent="Upload complete. Save the command to persist its blob reference."}
const drop=app.querySelector<HTMLElement>(".drop")!;drop.ondragover=event=>event.preventDefault();drop.ondrop=event=>{event.preventDefault();if(event.dataTransfer?.files)void upload(event.dataTransfer.files)};(commandForm.elements.namedItem("files") as HTMLInputElement).onchange=event=>{const input=event.currentTarget as HTMLInputElement;if(input.files)void upload(input.files);input.value=""};
commandForm.onsubmit=event=>{event.preventDefault();const form=new FormData(commandForm);const getUrl=(name:string,current?:Media)=>{const value=String(form.get(name)??"").trim();return value?{url:value}:current?.blob?current:undefined};const command:Command={id:editing??crypto.randomUUID(),command:String(form.get("command")).toLowerCase(),mode:form.get("sticker")?"sticker":"effect",image:getUrl("imageUrl",pending.image),audio:getUrl("audioUrl",pending.audio),video:getUrl("videoUrl",pending.video),durationSeconds:Number(form.get("duration")),cooldownSeconds:Number(form.get("cooldown")),volume:Number(form.get("volume")),width:String(form.get("width")),height:String(form.get("height")),mirrored:Boolean(form.get("mirrored"))};if(command.mode==="sticker")delete command.audio;const index=config.commands.findIndex(item=>item.id===command.id);if(index<0)config.commands.push(command);else config.commands[index]=command;commandForm.hidden=true;void saveAll();render()};
async function saveAll(){statusEl.textContent="Saving to PDS…";const response=await fetch(`/api/accounts/${encodeURIComponent(did)}/config`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)});if(response.ok){config=await response.json();statusEl.textContent="Saved to your PDS."}else statusEl.textContent="Save failed. Check media URLs and command values."}
async function load(){const response=await fetch("/api/session");if(!response.ok)return;did=(await response.json()).did;login.hidden=true;editor.hidden=false;app.querySelector(".did")!.textContent=did;app.querySelector(".effect-url")!.textContent=obsUrl("/effect/");app.querySelector(".board-url")!.textContent=obsUrl("/board/");const stored=await fetch(`/api/accounts/${encodeURIComponent(did)}/config`);config=stored.ok?await stored.json():{enabled:true,streamerDid:did,revision:"new",commands:[]};const enabled=app.querySelector<HTMLInputElement>(".enabled")!;enabled.checked=config.enabled;enabled.onchange=()=>{config.enabled=enabled.checked;void saveAll()};render()}
app.querySelector<HTMLButtonElement>(".new")!.onclick=()=>open();app.querySelector<HTMLButtonElement>(".cancel")!.onclick=()=>{commandForm.hidden=true};app.querySelector<HTMLButtonElement>(".logout")!.onclick=async()=>{await fetch("/oauth/logout",{method:"POST"});location.reload()};void load();
